<?php
return array(
	'name'=>array(
		'title'=>'归属名称:',
		'type'=>'text',
		'value'=>''
	),
	'title'=>array(
		'title'=>'顶部标识:',
		'type'=>'text',
		'value'=>''
	),
	'nums'=>array(
		'title'=>'隔壁动态:',
		'type'=>'text',
		'value'=>'3'
	),
	'is_share'=>array(
		'title'=>'分享朋友圈:',
		'type'=>'radio',
		'options'=>array(
			'1'=>'允许',
			'0'=>'禁止'
		),
	),
	'is_at'=>array(
		'title'=>'站外@朋友::',
		'type'=>'radio',
		'options'=>array(
			'1'=>'允许',
			'0'=>'禁止'
		),
	),
	'dsfjr'=>array(
		'title'=>'第三方接入:',
		'type'=>'text',
		'value'=>''
	),
	'jr_cache'=>array(
		'title'=>'接入缓存:',
		'type'=>'text',
		'value'=>'60'
	),
	'dsfsq'=>array(
		'title'=>'第三方授权:',
		'type'=>'text',
		'value'=>''
	),
	'sq_cache'=>array(
		'title'=>'接入缓存:',
		'type'=>'text',
		'value'=>'60'
	),
);
					